### PR TITLE
Fixed username query in the Bash script

### PR DESCRIPTION
**Pull request by Deuchnord**
The Bash script didn't ask the username, which caused a general problem to access the account on PROF.
This PR fixes this problem by asking the username before asking the password.

### CODE REVIEW

**Comment by calve** [comment]
I'm afraid it will be annoying to be prompted each time for your login name.
I suggest you to read the username from the ``PROF_LOGIN`` environment variable if set, and fallback asking user if it is not set.

Otherwise I'm glad to see that this script is still usefull, I strongly invite you to test the python version.

**Comment by Deuchnord** [comment]
Great idea to use an environment variable! I'll change that tomorrow :)

I already tested the Python script, but on my PC (and on those in the University), it doesn't start at all and says:

````
$ python3 prof/prof.py
Traceback (most recent call last):
  File "prof/prof.py", line 4, in <module>
    from init import initiate_session
  File "/home/jerome/Documents/prof/prof/init.py", line 1, in <module>
    import requests
ImportError: No module named 'requests'
````

Sorry for not having said for this issue, I was looking for the better way to report it :/

**Comment by WebTogz** [comment]
'requests' is an HTTP Python module, to download and install.
A simple "sudo pip install requests" (or "sudo easy_install requests") make the thing ;-)

**Comment by Deuchnord** [comment]
I don't have any program named `pip` nor `easy_install`, is that normal? oO
(Debian Testing)

Is the Bash script deprecated? I could maintain it if necesseray :)

**Comment by WebTogz** [comment]
'easy_install' is a Python package manager - 'pip' is a replacement.
I invite you to install one of them ('pip' is the better option) with aptitude ('sudo aptitude install python-pip' for 'pip')

**Comment by WebTogz** [comment]
The code is free - feel free to share your updates ;-)

**Comment by calve** [comment]
I just merged your changes (plus a few of mines to ensure consistency).
Sorry for the delay, I have a poor internet connection these days.

**Comment by Deuchnord** [comment]
No problem, thanks :)

**Pull request merged**
